
const influencer = {
    influencerId,
    userId,
    userProfileId,
    influencerPlatformId,
    influencerAgeListId,
    influencerFormatId,
    influencerTypeId,
    influencerTopicsId,
    audienceLocationId,
    influencerfullName,
    influencerAddress,
    influencerAge,
    influencerBio,
    influencerEmail,
    influencerFollowers,
    influencerGender,
    influencerRelationship,
    influencerPhone,
    influencerCostEstimateFrom,
    influencerCostEstimateTo,
    influencerNickName,
    influencerTypeName,
    influencerContentTopicName,
    influencerContentFormatName,
    audienceGender,
    audienceLocation,
    influencerEngagement,
    influencerPostsPerWeek,
    influencerLinkFb,
    influencerLinkInsta,
    influencerLinkTiktok,
    influencerLinkYoutube,
    influencerFollowFb,
    influencerFollowInsta,
    influencerFollowTikTok,
    influencerFollowYoutube,
    influencerInteractionFb,
    influencerInteractionInsta,
    influencerInteractionTiktok,
    influencerInteractionYoutube,
    audienceAgeFrom,
    audienceAgeTo
}

module.exports = influencer;